version: "3"

services:
  jenkins:
    image: jenkinsci/blueocean
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home

  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    user: root
    volumes:
      - ./verdaccio:$HOME/.config/verdaccio

  nginx:
    image: nginx
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
    depends_on:
      - jenkins
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

  dns:
    image: jpillora/dnsmasq
    restart: always
    ports:
      - 53:53/udp
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf