version: "3"

services:
  gitlab:
    container_name: gitlab
    hostname: gitlab.ekwing.com
    image: "ekwing/gitlab:${GITLAB_VERSION}"
    user: root
    privileged: true
    restart: always
    ports:
      - "10022:22"
    environment:
      VIRTUAL_HOST: gitlab.ekwing.com
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.ekwing.com'
        pages_external_url 'http://gitlab.ekwing.io/'
        unicorn['worker_processes'] = 2
        gitlab_pages['enable'] = true
        gitlab_rails['backup_keep_time'] = 604800
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'ekwing@moyi365.com'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab Admin'
        gitlab_rails['gitlab_email_reply_to'] = 'ekwing@moyi365.com'
        gitlab_rails['gitlab_ssh_host'] = 'gitlab.ekwing.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['lfs_storage_path'] = '/var/opt/gitlab/gitlab-rails/shared/lfs-objects'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.exmail.qq.com'
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = 'ekwing@moyi365.com'
        gitlab_rails['smtp_password'] = ''
        gitlab_rails['smtp_domain'] = 'exmail.qq.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab-runner/config:/etc/gitlab-runner
    extra_hosts:
      - "jenkins.ekwing.com:${BRIDGE_IP}"
      - "npm.ekwing.com:${BRIDGE_IP}"
    depends_on:
      - nginx-proxy

  jenkins:
    container_name: jenkins
    hostname: jenkins.ekwing.com
    image: "ekwing/jenkins:${JENKINS_VERSION}"
    restart: always
    user: root
    environment:
      - VIRTUAL_HOST=jenkins.ekwing.com
      - VIRTUAL_PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/data:/var/jenkins_home
      - ./jenkins/scripts:/root/scripts
    extra_hosts:
      - "gitlab.ekwing.com:${BRIDGE_IP}"
      - "npm.ekwing.com:${BRIDGE_IP}"
    depends_on:
      - nginx-proxy

  verdaccio:
    container_name: verdaccio
    hostname: npm.ekwing.com
    image: "verdaccio/verdaccio:${VERDACCIO_VERSION}"
    restart: always
    user: root
    environment:
      - VIRTUAL_HOST=npm.ekwing.com
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/plugins:/verdaccio/plugins
    depends_on:
      - nginx-proxy

  nginx-proxy:
    container_name: nginx-proxy
    image: "jwilder/nginx-proxy:${NGINX_VERSION}"
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${DEFAULT_SUBNET}"
