version: "3"

services:
  gitlab:
    container_name: gitlab
    hostname: gitlab.ekwing.com
    image: "gitlab/gitlab-ce:${GITLAB_VERSION}-ce.0"
    user: root
    privileged: true
    restart: always
    ports:
      - "10022:22"
    environment:
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.ekwing.com'
        pages_external_url 'http://gitlab.ekwing.io/'
        unicorn['worker_processes'] = 2
        gitlab_pages['enable'] = true
        gitlab_rails['backup_keep_time'] = 604800
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'ekwing@moyi365.com'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab Admin'
        gitlab_rails['gitlab_email_reply_to'] = 'ekwing@moyi365.com'
        gitlab_rails['gitlab_ssh_host'] = 'gitlab.ekwing.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['lfs_storage_path'] = '/var/opt/gitlab/gitlab-rails/shared/lfs-objects'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.exmail.qq.com'
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = 'ekwing@moyi365.com'
        gitlab_rails['smtp_password'] = ''
        gitlab_rails['smtp_domain'] = 'exmail.qq.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  gitlab-runner:
    container_name: gitlab-runner
    image: "gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}"
    restart: always
    user: root
    depends_on:
      - gitlab
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    container_name: jenkins
    hostname: jenkins.ekwing.com
    image: "jenkinsci/blueocean:${JENKINS_VERSION}"
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home

  verdaccio:
    container_name: verdaccio
    hostname: npm.ekwing.com
    image: "verdaccio/verdaccio:${VERDACCIO_VERSION}"
    restart: always
    user: root
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/plugins:/verdaccio/plugins

  nginx:
    container_name: nginx
    image: "nginx:${NGINX_VERSION}"
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gitlab
      - jenkins
      - verdaccio
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
