version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    ports:
      - 22:22
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://gitlab.ekwing.com'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  jenkins:
    image: jenkinsci/blueocean
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home

  verdaccio:
    image: verdaccio/verdaccio:4.x-next
    restart: always
    user: root
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/plugins:/verdaccio/plugins

  nginx:
    image: nginx
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gitlab
      - jenkins
      - verdaccio
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

  dns:
    image: jpillora/dnsmasq
    restart: always
    ports:
      - 53:53/udp
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf